// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using Backend.Entities;

namespace Backend
{
    public partial class RefreshToken
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string TokenHash { get; set; }
        public string TokenSalt { get; set; }
        public DateTime Ts { get; set; }
        public DateTime ExpiryDate { get; set; }
        public bool IsExpired => DateTime.UtcNow >= ExpiryDate;
        public DateTime Created { get; set; }
        public virtual User User { get; set; }
        public DateTime? Revoked { get; internal set; }
        public string RevokedByIp { get; internal set; }
        public string ReplacedByToken { get; internal set; }
        public bool IsActive => Revoked == null && !IsExpired;
    }
}