// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Backend.Entities
{
    public class User
    {

        public int Id { get; set; }
        public string Email { get; set; } = string.Empty;
        public string Password { get; set; } = string.Empty;
        public string PasswordSalt { get; set; } = string.Empty;
        public string FirstName { get; set; } = string.Empty;
        public string LastName { get; set; } = string.Empty;
        public DateTime Ts { get; set; }
        public string? DOB { get; set; }
        public bool Active { get; set; }
        public Role Role { get; set; }
        public string? VerificationToken { get; set; }
        public DateTime? Verified { get; set; }
        public DateTime? PasswordReset { get; set; }
        public DateTime Created { get; set; }
        public DateTime? Updated { get; set; }
        
        // Reset password fields
        public string? ResetToken { get; set; }
        public DateTime? ResetTokenExpires { get; set; }

        // MFA fields
        public string? PhoneNumber { get; set; }
        public bool MfaEnabled { get; set; }
        public string? MfaCode { get; set; }
        public DateTime? MfaCodeExpires { get; set; }

        [JsonIgnore]
        public List<RefreshToken> RefreshTokens { get; set; } = [];

        [JsonIgnore]
        public List<LocalTask> Tasks { get; set; } = [];
    }
}